steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy hello_world \
      --runtime python310 \
      --trigger-http \
      --allow-unauthenticated \
      --region us-central1 \
      --source .
